### ISSUE TITLE
Custom break prompt

### ISSUE THREAD

**Issue by xerus2000** [rcaelers/workrave#195]
Often, there's quite a few things I could do in a break - but since it is a break, it is also not the best idea to exert mental effort to recall what these things were. I'd love if I could add a custom text or even a custom command output (I use taskwarrior and have a report specifically for tasks that fit in a break) to be shown in the prompt for the break.
The custom text could be something like "Look out & around, get some water, roll on your massage roll" etc.

**Comment by xerus2000** [comment]
Could probably be solved with #105 - I could have a script that creates a notification with that info.

**Comment by wolftune** [comment]
The script idea would be nice, but I still think a default custom-text option would be good.

I just was comparing Workrave to the other alternatives that are also Free/Libre/Open, namely https://github.com/hovancik/stretchly and https://github.com/slgobinath/SafeEyes/ and https://github.com/tom-james-watson/breaktimer-app

The first two (Stretchly and SafeEyes) both have this feature and a set of default texts. It's a bit like the exercises feature of WorkRave, but customizable, text only, and shows up on screen with each micro-break.

I otherwise prefer the experience of WorkRave for the manner in which breaks are prompted (the others use system notifications as just yellow-light-style warnings and then they turn on the break no matter what). However, this one feature of the others is really nice.

**Comment by xeruf** [comment]
I am going with Stretchly for now, but still not quite happy.

> the others use system notifications and then they turn on the break no matter what, no way to avoid it

Well in Stretchly you can configure whether to allow postponing which is bound to Ctrl-X by default.
